# Generated by Django 4.1.2 on 2022-11-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDefault',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_to_send', models.TextField(blank=True, max_length=500, null=True)),
                ('email_label', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'email_default',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='JoinedData',
        ),
    ]
