# Generated by Django 4.1.2 on 2022-11-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('newapp', '0002_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'managed': False, 'verbose_name': 'Contract'},
        ),
        migrations.AlterModelOptions(
            name='joineddata',
            options={'managed': False, 'verbose_name': 'Data Point'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False, 'verbose_name': 'Person'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'managed': False, 'verbose_name': 'Position'},
        ),
        migrations.AlterModelOptions(
            name='posting',
            options={'managed': False, 'verbose_name': 'Posting'},
        ),
    ]
