# Generated by Django 4.1.2 on 2022-11-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_contract_options_alter_joineddata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDefault',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_to_send', models.CharField(blank=True, max_length=500, null=True)),
                ('email_label', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Email Default',
                'db_table': 'email_default',
                'managed': False,
            },
        ),
    ]
