# Generated by Django 4.1.2 on 2022-11-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'managed': False, 'verbose_name': 'List of Contract'},
        ),
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'managed': False, 'verbose_name': 'Employment Historie'},
        ),
        migrations.AlterModelOptions(
            name='joineddata',
            options={'managed': False, 'verbose_name': 'All Data Point'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False, 'verbose_name': 'All Person'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'managed': False, 'verbose_name': 'All Position'},
        ),
        migrations.AlterModelOptions(
            name='posting',
            options={'managed': False, 'verbose_name': 'All Posting'},
        ),
        migrations.AlterModelOptions(
            name='previousemployer',
            options={'managed': False, 'verbose_name': 'Previous Employer'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'managed': False, 'verbose_name': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='supervisors',
            options={'managed': False, 'verbose_name': 'Supervisor'},
        ),
        migrations.AlterModelOptions(
            name='workterm',
            options={'managed': False, 'verbose_name': 'Semester/Year Term'},
        ),
    ]
